### ISSUE TITLE
repr(TclProc) fails for a TclProc targeting a C command

### ISSUE THREAD

**Issue by NasaGeek** [flightaware/tohil#35]
No `proc_args` exist for C commands since we can't introspect them

Env: tohil 4.0.0
```python
I >>> tohil.TclProc("linsert")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/tohil-4.0.0-py3.7-freebsd-11.4-RELEASE-p9-amd64.egg/tohil/__init__.py", line 415, in __repr__
    return f"<class 'TclProc' '{self.proc}', args '{repr(self.proc_args)}>"
AttributeError: 'TclProc' object has no attribute 'proc_args'
```

**Comment by resuna** [comment]
Isn't this the expected result?

**Comment by mutability** [comment]
repr throwing AttributeError is unexpected

**Comment by resuna** [comment]
What does it do for `tohil.TclProc("shenanigans")`?

**Comment by mutability** [comment]
Note that it's the REPL's call to __repr__ to stringize the constructed
object for display that's failing here, not the object ctor itself.

**Comment by resuna** [comment]
So perhaps the ctor should fail if the target is not actually a proc?

**Comment by mutability** [comment]
I'm not sure that's a useful distinction, the user of TclProc is unlikely
to know or care about which mechanism was used to define the command.

>

**Comment by resuna** [comment]
Ah, it's misnamed as well. Shoudl be TclCommand if it's not just for procs.

**Comment by lehenbauer** [comment]
Fixed by https://github.com/flightaware/tohil/commit/a88c3ae47ae04ad0e22148390b5297a6efce715b
