### ISSUE TITLE
There is currently no way to pass None to a Python function when using `::tohil::call`

### ISSUE THREAD

**Issue by NasaGeek** [flightaware/tohil#37]
This may not have a satisfactory solution, but I think it's something worth thinking about (special ::tohil::NONE sentinel value perhaps?). This is typically easy to work around as Python functions most often treat None as a default value rather than it having a specific meaning, so we can just not pass the arg at all.

**Comment by lehenbauer** [comment]
A branch that implements a sentinel, `tohil::NONE`, is available for testing: https://github.com/flightaware/tohil/tree/issue-37-pass-none-to-call

**Comment by lehenbauer** [comment]
Fixed on mainline branch, including tests and updated docs.
