### ISSUE TITLE
Modifying a tcl list via tclobj replaces list entirely

### ISSUE THREAD

**Issue by NasaGeek** [flightaware/tohil#38]
Not sure if I'm doing the wrong thing here, but it's not really what I expected.
Expected behavior: I can modify a tcl list in place by applying Python list methods to a tclvar (really a tclobj)
Actual behavior:
```python
Python 3.7.6 (default, Jan 30 2020, 01:17:40)
[Clang 8.0.0 (tags/RELEASE_800/final 356365)] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
I >>> import tohil
I >>> p = tohil.tclvar("auto_path")
I >>> p
<tohil.tclobj: '/usr/local/lib/tcl8.6 /usr/local/lib ./lib'>
I >>> p.insert(0, "/usr/local/lib")
I >>> p
<tohil.tclobj: '/usr/local/lib'>
```
I'm seeing this with methods other than `insert`, too, like `append`.

**Comment by lehenbauer** [comment]
Fixed on main branch, including new tests that fail on prior versions of tohil and succeed on this one.  Leaving the issue open for a while as the changes weren't quite trivial and something else miiight turn up.
