### ISSUE TITLE
Tcl sometimes tries to re-require tohil, results in namespace creation error

### ISSUE THREAD

**Issue by NasaGeek** [flightaware/tohil#49]
When running in Apache Rivet, we've noticed that rarely Tcl will "forget" that it's already gone through the "package require" process for tohil. It will attempt to do so again when tohil is required, at which point an error is returned because tohil tries to create the ::tohil namespace again. The traceback looks like this:
```
can't create namespace "::tohil": already exists
    while executing
"load /usr/local/lib/tohil4.0.0/libtohil4.0.0.so tohil"
    ("package ifneeded tohil 4.0.0" script)
    invoked from within
"package require tohil"
    (procedure "fa_main_navigation" line 7)
    invoked from within
-- snip --
```
This issue is almost always limited to a single Apache child (though we've seen at least one case where it affected several children).

Is it possible we're encountering a case where `package provide` is never getting called when requiring tohil?

**Comment by lehenbauer** [comment]
Please try release v4.0.1.

**Comment by lehenbauer** [comment]
Well it gets further but still screws up.  v4.0.2 will hopefully at least provide a better error message.  sad face.

**Comment by lehenbauer** [comment]
Have you seen any problems since 4.0.3?  I don't.  It's a mystery.  Maybe the install wasn't clean previously?

**Comment by lehenbauer** [comment]
We haven't seen this recur in a while, under fairly heavy use.  Can't definitively say it's fixed but I think cleaning out all the installs is a factor.  4.1.1 does a package require -exact to try to make sure it finds the right tcl-side tohil after import tohil from python.  (for native tcl, it's up to tcl's package manager to find the right package.)
