### ISSUE TITLE
Error occurs when importing tohil 4.1.0 on some installs

### ISSUE THREAD

**Issue by NasaGeek** [flightaware/tohil#50]
When trying to import tohil 4.1.0 in certain environments, the following error occurs
```
import tohil
  File "/prj/venv/lib/python3.6/site-packages/tohil-4.1.0-py3.6-linux-x86_64.egg/tohil/__init__.py", line 281, in <module>
    from tohil._tohil import (
SystemError: execution of module tohil._tohil failed without setting an exception
```
I believe this was seen on 2695b5c1.

**Comment by lehenbauer** [comment]
I wasn't able to repro this on a similar x86_64 Linux machine.  Can you build the latest and see if it still has the problem?  Thanks.

**Comment by lehenbauer** [comment]
We haven't seen this again.  We've retooled stuff and we think it's better.  Please refile if it happens again.  Thanks.
