### ISSUE TITLE
Deleting a subinterpreter that's `package require`d tohil causes a segfault

### ISSUE THREAD

**Issue by NasaGeek** [flightaware/tohil#62]
This is best run noninteractively. There are other issues that come up when trying to run this in a python shell.

```py
import tohil
subinterp = tohil.call("interp", "create", to=str)
tohil.call(subinterp, "eval", "package require tohil")
tohil.call("interp", "delete", subinterp)
```

So creating a subinterpreter and requiring tohil in there, then trying to delete the subinterpreter, causes a segfault.

**Comment by lehenbauer** [comment]
Your example case works now when run with tohil built against the push-pop-threadstate branch.

**Comment by lehenbauer** [comment]
The commits that fix this have been merged with the main branch.  Tohil 4.2.1 will be released shortly.
