### ISSUE TITLE
Strange behavior arises in a python shell if you `package require tohil` in a Tcl subinterpreter

### ISSUE THREAD

**Issue by NasaGeek** [flightaware/tohil#64]
Seems like the globals get wiped out. Same issue does not arise when doing the `package require` in a normal tohil call.
```py
Python 3.8.11 (default, Jun 28 2021, 10:57:31)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
+>>> import tohil
+>>> subinterp = tohil.call("interp", "create")
+>>> subinterp
<tohil.tclobj: 'interp0'>
+>>> subinterp = str(subinterp)
+>>> tohil.call(subinterp, "eval", "package require tohil")
<tohil.tclobj: '4.2.0'>
subinterp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'subinterp' is not defined
```

Suddenly, `subinterp` is undefined. We also lose our prompt for some reason.

**Comment by NasaGeek** [comment]
@lehenbauer had some good insight here that the reason the globals are wiped out is because we're being put into a new python subinterpreter.

**Comment by lehenbauer** [comment]
For some reason the "package require tohil" is connecting you interactively to the new python subinterpreter that was created for the child interpreter.  And you don't get a command prompt.  And ctrl-D exits the program.  So there's something about the way we create the subinterpreter that causes it to go interactive like that.  So far, I don't get it.

It works fine from Tcl:

```
 $ tclsh
 % package require tohil
4.2.0
 % set subinterp [interp create]
interp0
 % $subinterp eval "package require tohil"
4.2.0
```

As an aside, you don't need the `subinterp = str(subinterp)` in your example.

**Comment by lehenbauer** [comment]
This is due to the thread state needing to be restored to the parent python interpreter's state after a "package require tohil" from a tcl child interpreter causes a new python subinterpreter to be created.  It's fixed in the issue-64-tohil-in-tcl-child-interpreter branch, but currently we get a python fatal error on exit unless all tcl child interpreters are explicitly destroyed.

**Comment by NasaGeek** [comment]
We need to swap back to the Python parent thread state every time we return from Tcl to Python to ensure that we're maintaining the right thread state (we swap to the child on entry so we must swap back on exit). Otherwise, the issue reoccurs when running something like 
```
tohil.call(subinterp, "eval", "tohil::exec {print('hello world')}")
```
even with your fix.

**Comment by NasaGeek** [comment]
I've got some hacky stuff at https://github.com/flightaware/tohil/tree/more-subinterp-tests that might be of some interest.

**Comment by lehenbauer** [comment]
This is fixed in the main branch and will appear in release 4.2.1, which will be released shortly.
