### ISSUE TITLE
Raising exception from a Tcl-hosted Python subinterpreter that hasn't imported tohil yet causes segfault

### ISSUE THREAD

**Issue by NasaGeek** [flightaware/tohil#67]
repro.tcl
```tcl
package require tohil
set interp [interp create]
$interp eval {
	package require tohil
	tohil::exec {print('Hello World')}
	tohil::exec {raise Exception()}
}
```
The above code prints Hello World and then segfaults. This occurs because we're catching any exceptions that come from Python and trying to use tohil's `handle_exception()` function to process them, except that this Python subinterpreter hasn't yet imported tohil. We actually have code to handle this case (we call `Tohil_ReturnTclError()` if we couldn't find tohil.handle_exception()), but then `tohil_tcl_return()` notices there's an unhandled Python exception and we enter into an infinite loop of `tohil_tcl_return()` -> `Tohil_ReturnExceptionToTcl()` -> `Tohil_ReturnTclError()` calling back and forth to each other.

**Comment by NasaGeek** [comment]
Oh it seems like this is happening because if we swap the threadstate back to the parent after creating our new subinterpreter then we don't properly perform the Python setup in `Tohil_Init()` that occurs after calling `tohil_setup_subinterp()`.

**Comment by NasaGeek** [comment]
This is fixed in https://github.com/flightaware/tohil/commit/963c09a3baeaf633d68e1a9017f7dbe8cd819173 by ensuring we swap back to the parent thread state only after the child has been fully set up.

**Comment by lehenbauer** [comment]
Confirmed.
